# Generated by Django 6.0.1 on 2026-05-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyosu_campus_navi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='language',
            field=models.CharField(default='JA', max_length=16),
        ),
    ]
