# Generated by Django 6.0.1 on 2026-05-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyosu_campus_navi', '0002_alter_userinfo_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='building_name',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='section_name',
            new_name='section',
        ),
        migrations.AddField(
            model_name='edge',
            name='estimated_travel_time',
            field=models.BigIntegerField(null=True, verbose_name='推定移動時間'),
        ),
        migrations.AlterField(
            model_name='section',
            name='bottom_right_x',
            field=models.BigIntegerField(null=True, verbose_name='区画の右下x座標'),
        ),
        migrations.AlterField(
            model_name='section',
            name='bottom_right_y',
            field=models.BigIntegerField(null=True, verbose_name='区画の右下y座標'),
        ),
        migrations.AlterField(
            model_name='section',
            name='business_hour',
            field=models.CharField(max_length=1023, null=True, verbose_name='営業時間'),
        ),
        migrations.AlterField(
            model_name='section',
            name='capacity',
            field=models.BigIntegerField(null=True, verbose_name='収容人数'),
        ),
        migrations.AlterField(
            model_name='section',
            name='top_left_x',
            field=models.BigIntegerField(null=True, verbose_name='区画の左上x座標'),
        ),
        migrations.AlterField(
            model_name='section',
            name='top_left_y',
            field=models.BigIntegerField(null=True, verbose_name='区画の左上y座標'),
        ),
        migrations.AlterField(
            model_name='section',
            name='usage',
            field=models.CharField(max_length=1023, null=True, verbose_name='使用用途'),
        ),
    ]
