# Generated by Django 6.0.1 on 2026-05-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyosu_campus_navi', '0003_rename_building_name_section_building_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='business_hour',
            new_name='business_hours',
        ),
        migrations.AlterField(
            model_name='edge',
            name='estimated_travel_time',
            field=models.BigIntegerField(null=True, verbose_name='推定移動時間(ミリ秒)'),
        ),
    ]
