# Generated by Django 6.0.1 on 2026-05-25 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyosu_campus_navi', '0004_rename_business_hour_section_business_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='goal_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_section', to='toyosu_campus_navi.section', verbose_name='目的地'),
        ),
    ]
