# Generated by Django 6.0.1 on 2026-06-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toyosu_campus_navi', '0005_alter_history_goal_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='History_ID',
            new_name='history_ID',
        ),
    ]
