# Generated by Django 6.0.1 on 2026-06-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyosu_campus_navi', '0006_rename_history_id_history_history_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=127, verbose_name='タイトル'),
        ),
    ]
