# Generated by Django 6.0.1 on 2026-06-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyosu_campus_navi', '0007_alter_notice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='estimated_travel_time',
            field=models.BigIntegerField(default=0, verbose_name='推定移動時間(ミリ秒)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='bottom_right_x',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='区画の右下x座標'),
        ),
        migrations.AlterField(
            model_name='section',
            name='bottom_right_y',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='区画の右下y座標'),
        ),
        migrations.AlterField(
            model_name='section',
            name='business_hours',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='営業時間'),
        ),
        migrations.AlterField(
            model_name='section',
            name='capacity',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='収容人数'),
        ),
        migrations.AlterField(
            model_name='section',
            name='top_left_x',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='区画の左上x座標'),
        ),
        migrations.AlterField(
            model_name='section',
            name='top_left_y',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='区画の左上y座標'),
        ),
        migrations.AlterField(
            model_name='section',
            name='usage',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='使用用途'),
        ),
    ]
